import type { ReportSourceRef } from './types'

export const PROFESSIONAL_REPORT_SOURCE_MAP: ReportSourceRef[] = [
  {
    id: 'daily_sales.revenue',
    label: 'Ventas registradas',
    tables: ['daily_sales'],
    calculation: 'Suma de daily_sales.revenue_total en el periodo.',
    kind: 'actual',
    requiredFor: ['executive_summary', 'sales', 'profitability'],
  },
  {
    id: 'daily_sales.channels',
    label: 'Ventas por canal',
    tables: ['daily_sales'],
    calculation: 'Comparación entre revenue_total y revenue_dine_in + revenue_takeout + revenue_delivery.',
    kind: 'actual',
    requiredFor: ['sales', 'data_appendix'],
  },
  {
    id: 'operating_expenses.amount',
    label: 'Gastos operativos',
    tables: ['operating_expenses'],
    calculation: 'Suma de operating_expenses.amount agrupada por categoría.',
    kind: 'actual',
    requiredFor: ['executive_summary', 'costs', 'profitability'],
  },
  {
    id: 'monthly_targets.targets',
    label: 'Objetivos mensuales',
    tables: ['monthly_targets'],
    calculation: 'Objetivos de ingresos, COGS y personal aplicables al periodo.',
    kind: 'actual',
    requiredFor: ['sales', 'costs', 'profitability'],
  },
  {
    id: 'employees.active',
    label: 'Plantilla activa',
    tables: ['employees'],
    calculation: 'Conteo de empleados con status ACTIVE y distribución por rol.',
    kind: 'actual',
    requiredFor: ['staff'],
  },
  {
    id: 'shifts.cost',
    label: 'Coste de turnos',
    tables: ['shifts'],
    calculation: 'Suma de actual_cost cuando existe; si no, estimated_cost.',
    kind: 'actual',
    requiredFor: ['staff', 'profitability'],
  },
  {
    id: 'suppliers.scorecard',
    label: 'Scorecard de proveedores',
    tables: ['suppliers'],
    calculation: 'Media de reliability_score y tendencia declarada por proveedor.',
    kind: 'actual',
    requiredFor: ['suppliers'],
  },
  {
    id: 'invoices.completed_spend',
    label: 'Compras por factura completada',
    tables: ['invoices'],
    calculation: 'Suma de invoices.total_amount con status completed en el periodo.',
    kind: 'actual',
    requiredFor: ['suppliers', 'costs'],
  },
  {
    id: 'daily_recipe_sales.quantity',
    label: 'Ventas por receta',
    tables: ['daily_recipe_sales'],
    calculation: 'Suma de quantity_sold por recipe_id dentro del periodo.',
    kind: 'actual',
    requiredFor: ['menu_performance'],
  },
  {
    id: 'recipes.recipe_cost',
    label: 'Coste y PVP de receta',
    tables: ['recipes'],
    calculation: 'Cruce de ventas por receta con recipes.current_cost y recipes.selling_price actuales.',
    kind: 'actual',
    requiredFor: ['menu_performance'],
  },
  {
    id: 'menu_engineering.report',
    label: 'Matriz BCG guardada',
    tables: ['menu_reports', 'menu_report_items'],
    calculation: 'Ultimo reporte Menu Engineering ANALYZED del restaurante cuyo rango esta contenido en el periodo del informe.',
    kind: 'derived',
    requiredFor: ['menu_engineering'],
  },
]
